version: '3'

services:
  # app:
  #   build:
  #     context: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./app:/app
  #     - ./common:/root
  #   command: >
  #     sh -c "python manage.py wait_for_db &&
  #            python manage.py migrate &&
  #            python manage.py runserver 0.0.0.0:8080"
  #   environment:
  #     - DB_HOST=db
  #     - DB_NAME=app
  #     - DB_USER=letsfind
  #     - DB_PASS=letsfind
  #   depends_on:
  #     - db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    #entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=letsfind
      - MYSQL_PASSWORD=letsfind
      - MYSQL_ROOT_PASSWORD=letsfind
